/* Staging db*/
CREATE TABLE staging (
    eff_date text,
    index_alias text,
    security_alias text,
    eff_date text,
    index_alias text,
    security_alias text,
    cusip text,
    ticker text,
    description text,
    country text,
    currency text,
    coupon text,
    mat_dt text,
    rating text,
    fe_sector text,
    class_1 text,
    class_2 text,
    class_3 text,
    class_4 text,
    price text,
    moddur text,
    effdur text,
    oas text,
    ytm text,
    sdur text,
    mv_bom text,
    mv text,
    mw text,
    day_tot text,
    day_ex text,
    mtd_tot text,
    mtd_ex text,
    dc text,
    sdc text,
    mv_tot text,
    dur_cell text
);

/* Copy data from csv to staging db */
COPY staging from "/Users/aditya/Documents/Python/proj/data/universe.csv"
DELIMITER ','
CSV HEADER;

CREATE TABLE main_table (
    eff_date date,
    index_alias text,
    security_alias text,
    cusip text,
    ticker text,
    description text,
    country text,
    currency text,
    coupon text,
    mat_dt text,
    rating text,
    fe_sector text,
    class_1 text,
    class_2 text,
    class_3 text,
    class_4 text,
    price numeric,
    moddur numeric,
    effdur numeric,
    oas numeric,
    ytm numeric,
    sdur numeric,
    mv_bom numeric,
    mv numeric,
    mw numeric,
    day_tot numeric,
    day_ex numeric,
    mtd_tot numeric,
    mtd_ex numeric,
    dc numeric,
    sdc numeric,
    mv_tot numeric,
    dur_cell text
);

/* move to the main table */
INSERT INTO main_table
    SELECT
        TO_DATE(eff_date, 'M/DD/YYYY'),
        index_alias,
        security_alias,
        cusip,
        ticker,
        description,
        country,
        currency,
        coupon,
        mat_dt,
        rating,
        fe_sector,
        class_1,
        class_2,
        class_3,
        class_4,
        CAST(price AS numeric),
        CAST(moddur AS numeric),
        CAST(effdur AS numeric),
        CAST(oas AS numeric),
        CAST(ytm AS numeric),
        CAST(sdur AS numeric),
        CAST(mv_bom AS numeric),
        CAST(mv AS numeric),
        CAST(mw AS numeric),
        CAST(day_tot AS numeric),
        CAST(day_ex AS numeric),
        CAST(mtd_tot AS numeric),
        CAST(mtd_ex AS numeric),
        CAST(dc AS numeric),
        CAST(sdc AS numeric),
        CAST(mv_tot AS numeric),
        dur_cell
    FROM staging;
